### ISSUE TITLE
Adding legend entries is clunky

### ISSUE THREAD

**Issue by ahalota** [mikeskaug/Leaflet.Legend#2]
It seems a lot of the requirements are for the user to format the legend, which is what I was hoping this plugin would do for me (the sample code you provided for #legend is good though).

It would be nice to reformat this plugin a little so that most of the content is given as an option to the plugin, which then creates the html for the user. For example, an option could be 

'legendContent': { 
     'Trail' : {type: 'line', color: '#ff0000'}, 
     'Bike Path': {type: 'img', 'url': '/img/bikePath.png'}, 
     'City' : {type: 'circle-fill', color: 'red'}
}

**Comment by mikeskaug** [comment]
I think that's a very good idea. I often want control over the html, but I agree that in many cases, providing a few options and allowing the plugin to construct the html would be more useful.

Unfortunately, I don't currently have time to implement this change, but I welcome contributions and  I will reopen this issue if start working on it.
