### ISSUE TITLE
demo link is broken

### ISSUE THREAD

**Issue by slead** [mikeskaug/Leaflet.Legend#3]
The link in your readme is broken - it seems that it should point to http://michaelskaug.com/projects/OpenTrailMap/ (not http://michaelskaug.com/projects/OpenTrails/)

**Comment by mikeskaug** [comment]
Thanks @slead! You're exactly right. I made the change: https://github.com/mikeskaug/Leaflet.Legend/commit/7ee6f86aedfbbe244509ad5a52754ff96bd96fed
